#!/usr/bin/python

#
#  All rights reserved (c) 2014-2018 CEA/DAM.
#
#  This file is part of Phobos.
#
#  Phobos is free software: you can redistribute it and/or modify it under
#  the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation, either version 2.1 of the License, or
#  (at your option) any later version.
#
#  Phobos is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with Phobos. If not, see <http://www.gnu.org/licenses/>.
#

import psycopg2
import json
import sys

"""
Convert phobos database
  * from 0 (phobos v1.0) to 1 (phobos v1.1):
  - update db schema
  - retrieve all entries from extent and media and set the json integer fields
    with the appropriate type.
  * from 1 (phobos v1.1) to 2 (phobos v1.2):
  - media and device model are updated from enum type to varchar
"""

CONN_STR = "dbname='phobos' user='phobos' host='localhost' password='phobos'"

DB_V_PHOBOS_V = (("1.0",), ("1.1",), ("1.2",))

class Migrator:
    """StrToInt JSONB conversion engine"""
    def __init__(self, **kwargs):
        self.conn = None

    def connect(self):
        self.conn = psycopg2.connect(CONN_STR)

    def disconnect(self):
        self.conn.close()
        self.conn = None

    def convert_schema_0_to_1(self):
        """
        DB schema changes:
        - drop type::extent_lyt_type
        - add media::fs_label after fs_type with the previous value of 'id'
        - extent:
            * pk of extent is only oid
            * drop field copy_num
            * drop field lyt_type
            * lyt_info='{"name":"simple","major":0,"minor":1}'
        """
        cur = self.conn.cursor()
        cur.execute("""
-- column order doesn't matter
ALTER TABLE media ADD COLUMN fs_label VARCHAR(32) DEFAULT '' NOT NULL;

-- First remove PRIMARY KEY attribute of former PRIMARY KEY
ALTER TABLE extent DROP CONSTRAINT extent_pkey;
-- Then set the new PRIMARY KEY
ALTER TABLE extent ADD PRIMARY KEY (oid);

-- drop fields copy_num and lyt_type
ALTER TABLE extent DROP COLUMN copy_num;
ALTER TABLE extent DROP COLUMN lyt_type;

-- set layout info for existing extents
UPDATE extent SET lyt_info='{"name":"simple","major":0,"minor":1}';

-- Drop the type once no column use it
-- Don't precise 'IF EXISTS' as the DB schema is supposed to be 1.0
-- so the type is supposed to exist.
DROP TYPE extent_lyt_type;""")
        self.conn.commit()
        cur.close()

    def convert_extent(self):
        update = []
        cur = self.conn.cursor()
        cur.execute("""SELECT oid, extents FROM extent""")
        for row in cur.fetchall():
            attr = json.loads(row[1])
            attr[0]['sz'] = int(attr[0]['sz'])
            update.append((row[0], attr))

        for u in update:
            qry = "UPDATE extent SET extents='%s' WHERE oid='%s'" % \
                (json.dumps(u[1]), u[0])
            cur.execute(qry)
        self.conn.commit()
        cur.close()

    def convert_media(self):
        update = []
        cur = self.conn.cursor()
        cur.execute("""SELECT id, stats FROM media""")
        for row in cur.fetchall():
            stats = json.loads(row[1])
            for f in ('nb_obj', 'last_load', 'nb_errors', 'logc_spc_used',
                      'phys_spc_free', 'phys_spc_used'):
                if stats.has_key(f):
                    stats[f] = int(stats[f])
            update.append((row[0], stats))

        for u in update:
            qry = "UPDATE media SET stats='%s' WHERE id='%s'" % \
                (json.dumps(u[1]), u[0])
            cur.execute(qry)
        self.conn.commit()
        cur.close()

    def convert_0_to_1(self):
        """Convert DB from model 0 (until phobos v1.0) to 1 (phobos v1.1)"""
        self.connect()
        self.convert_schema_0_to_1()
        self.convert_extent()
        self.convert_media()
        self.disconnect()

    def convert_schema_1_to_2(self):
        """
        DB schema changes:
        - device.id    : from varchar(32) to varchar(255)
        - media.id     : from varchar(32) to varchar(255)
        - device.model : from enum to varchar(32)
        - media.model  : from enum top varchar(32)
        """
        cur = self.conn.cursor()
        #Alter model from enum to varchar(32) and drop old enum types
        cur.execute("""
            -- increase device id size from 32 to 255
            ALTER TABLE device ALTER id TYPE varchar(255);

            -- increase media id size from 32 to 255
            ALTER TABLE media ALTER id TYPE varchar(255);

            -- device model from enum to varchar(32)
            ALTER TABLE device ALTER model TYPE varchar(32);

            -- media model from enum to varchar(32)
            ALTER TABLE media ALTER model TYPE varchar(32);

            -- drop old dev_model type.
            DROP TYPE dev_model;

            -- drop old media_model type.
            DROP TYPE tape_model;"""
        )
        self.conn.commit()
        cur.close()

    def convert_1_to_2(self):
        """Convert DB from model 1 (phobos v1.1) to 2 (phobos v1.2)"""
        self.connect()
        self.convert_schema_1_to_2();
        self.disconnect()

    def convert(self, old_model, new_model):
        """Convert DB from old_model to new_model"""
        convert_functions = {(0,1) : self.convert_0_to_1,
                             (1,2) : self.convert_1_to_2}
        for current in range(old_model, new_model):
            if (current, current+1) not in convert_functions:
                print "Unable to convert from model %s to %s." % \
                                                        (current, current + 1)
                sys.exit(1)

        for current in range(old_model, new_model):
            convert_functions[(old_model, new_model)]()

def main(args=sys.argv):
    print "DB MODEL : corresponding Phobos versions"
    db_v_index=0
    for phobos_v in DB_V_PHOBOS_V:
        print str(db_v_index) + " : " + str(phobos_v)
        db_v_index += 1
    old_model = int(raw_input("Which is your old existing db model : "))
    new_model = int(raw_input("Which is the db model you aim at : "))
    if old_model < 0 or old_model >= len(DB_V_PHOBOS_V):
        print "Your old existing db model doesn't exist."
        print str(old_model) + "is not between 0 and " + str(len(DB_V_PHOBOS_V))
        sys.exit(1)

    if new_model < 0 or new_model >= len(DB_V_PHOBOS_V):
        print "The aimed db model doesn't exist."
        print str(new_model) + "is not between 0 and " + str(len(DB_V_PHOBOS_V))
        sys.exit(1)

    if old_model >= new_model:
        print "The old_model (%s) is equal or younger than the target one (%s)"\
                                                        % (old_model, new_model)
        sys.exit(1)

    print "Your are about to upgrade database from model %s (phobos version "\
          "%s) to model %s (phobos version %s)." % (
              old_model, DB_V_PHOBOS_V[old_model], new_model,
              DB_V_PHOBOS_V[new_model]
          )
    go = raw_input("Do you want to continue? [y/N]: ")
    if go != 'y':
        sys.exit(1)

    Migrator().convert(old_model, new_model)

if __name__ == '__main__':
    main()

# -*- mode: Python; c-basic-offset: 4; indent-tabs-mode: nil; -*-
# vim:expandtab:shiftwidth=4:tabstop=4:ft=python:
