# Use latest AlmaLinux image as base for Podman Build from Dockerfiles
FROM almalinux:latest

RUN dnf install -y 'dnf-command(config-manager)'

# Enable the CRB repository, which contains some dependencies
RUN dnf config-manager --set-enabled crb
RUN dnf install epel-release -y

RUN dnf -y install python3-devel postgresql-devel glib2-devel jansson-devel libattr-devel libini_config-devel openssl-devel sg3_utils-devel protobuf-c-devel systemd autoconf automake libtool make openssl-devel xxhash-devel libcmocka-devel postgresql-server postgresql-contrib glib2 jansson libini_config openssl attr libattr python3 python3-PyYAML python3-clustershell python3-psycopg2 python3-tabulate python3-argcomplete protobuf protobuf-c xxhash-libs libuuid libuuid-devel gcc gdb valgrind vim git bc procps diffutils xxhash rpm-build jq kmod sudo python3-sphinx ctags

RUN mkdir -p /var/run/postgresql
RUN chown -R postgres: /var/run/postgresql
RUN sudo -u postgres bash -c 'initdb -D /var/lib/pgsql/db'

COPY postgres_script.sh /var/lib/pgsql

# Notes:
#   - you must run your container with the SYS_ADMIN capacity added, as some
#     tests modify the container's hostname: --cap-add SYS_ADMIN
#   - when running the container, you must start the PostGreSQL service using
#     the following command:
#     "sudo -u postgres bash -c '/var/lib/pgsql/postgres_script.sh'
